/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.Bairstow;
import metodos.Evaluador;
import metodos.Ferrari;
import metodos.Horner;
import metodos.Muller;
import metodos.Secante;
import metodos.Tartaglia;

/**
 *
 * @author villa
 */
public class InterfazMetodos extends javax.swing.JFrame {

    Evaluador eva = new Evaluador();

    /**
     * Creates new form InterfazMetodos
     */
    public InterfazMetodos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbFunciones = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFunciones = new javax.swing.JPanel();
        pnlTartaglia = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTartaglia1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTartaglia2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTartaglia3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDicriminante = new javax.swing.JTextField();
        pnlSecante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRaizSecante = new javax.swing.JTextField();
        txtErrorSecante = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSecante = new javax.swing.JTable();
        pnlFerrari = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFerrari3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFerrari2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFerrari1 = new javax.swing.JTextField();
        txtFerrari4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pnlHorner = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRaizHorner = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtErrorHorner = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorner = new javax.swing.JTable();
        pnlMuller = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtRaizMuller = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtErrorMuller = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMuller = new javax.swing.JTable();
        pnlBairstow = new javax.swing.JPanel();
        lblBairstow = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBairstow = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMinB = new javax.swing.JTextField();
        txtMaxB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        cmbFunciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una funcion", "x^3 + 3x - 1", "x^3 - 4.65x^2 - 49.92x - 76.69", "x^4 + x^3 + 0.56x^2 - 1.44x - 2.88", "x^4 - 3x^2 + 5x + 2", "x^5 - 3x^4 - 23x^3 + 55x^2 + 74x - 120", "x^6 - 7x^4 + x^3 - 1", "ln(1+x) - cos(x)", "10*sin(x) + 3*cos(x)", "e^3(x-1) - ln(x-1)^2 + 1", "cos(0.785 - x*sqrt(1+x^2))" }));

        btnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        pnlFunciones.setBackground(new java.awt.Color(0, 0, 0));

        pnlTartaglia.setBackground(new java.awt.Color(255, 255, 255));
        pnlTartaglia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTartaglia.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tartaglia");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Raiz:");

        txtTartaglia1.setEditable(false);
        txtTartaglia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Raiz:");

        txtTartaglia2.setEditable(false);
        txtTartaglia2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Raiz:");

        txtTartaglia3.setEditable(false);
        txtTartaglia3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Discriminante: ");

        txtDicriminante.setEditable(false);
        txtDicriminante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlTartagliaLayout = new javax.swing.GroupLayout(pnlTartaglia);
        pnlTartaglia.setLayout(pnlTartagliaLayout);
        pnlTartagliaLayout.setHorizontalGroup(
            pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTartagliaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia3))
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia1)))
                .addGap(28, 28, 28)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDicriminante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        pnlTartagliaLayout.setVerticalGroup(
            pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTartagliaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDicriminante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTartaglia1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTartaglia2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTartaglia3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pnlSecante.setBackground(new java.awt.Color(255, 255, 255));
        pnlSecante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSecante.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Secante");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Raiz:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Error:");

        txtRaizSecante.setEditable(false);
        txtRaizSecante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtErrorSecante.setEditable(false);
        txtErrorSecante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblSecante.setModel(new DefaultTableModel()
        );
        tblSecante.setEnabled(false);
        jScrollPane3.setViewportView(tblSecante);

        javax.swing.GroupLayout pnlSecanteLayout = new javax.swing.GroupLayout(pnlSecante);
        pnlSecante.setLayout(pnlSecanteLayout);
        pnlSecanteLayout.setHorizontalGroup(
            pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlSecanteLayout.createSequentialGroup()
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSecanteLayout.setVerticalGroup(
            pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlSecanteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaizSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlFerrari.setBackground(new java.awt.Color(255, 255, 255));
        pnlFerrari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFerrari.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ferrari");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Raiz:");

        txtFerrari3.setEditable(false);
        txtFerrari3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFerrari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFerrari3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Raiz:");

        txtFerrari2.setEditable(false);
        txtFerrari2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Raiz:");

        txtFerrari1.setEditable(false);
        txtFerrari1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtFerrari4.setEditable(false);
        txtFerrari4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Raiz:");

        javax.swing.GroupLayout pnlFerrariLayout = new javax.swing.GroupLayout(pnlFerrari);
        pnlFerrari.setLayout(pnlFerrariLayout);
        pnlFerrariLayout.setHorizontalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari2))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFerrariLayout.setVerticalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFerrari1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFerrari2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFerrari4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFerrari3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pnlHorner.setBackground(new java.awt.Color(255, 255, 255));
        pnlHorner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlHorner.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Horner");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Raiz:");

        txtRaizHorner.setEditable(false);
        txtRaizHorner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Error:");

        txtErrorHorner.setEditable(false);
        txtErrorHorner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblHorner.setModel(new DefaultTableModel());
        tblHorner.setEnabled(false);
        jScrollPane2.setViewportView(tblHorner);

        javax.swing.GroupLayout pnlHornerLayout = new javax.swing.GroupLayout(pnlHorner);
        pnlHorner.setLayout(pnlHornerLayout);
        pnlHornerLayout.setHorizontalGroup(
            pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHornerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnlHornerLayout.createSequentialGroup()
                        .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizHorner, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorHorner, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlHornerLayout.setVerticalGroup(
            pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHornerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHornerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaizHorner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorHorner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlMuller.setBackground(new java.awt.Color(255, 255, 255));
        pnlMuller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMuller.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Muller");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Raiz:");

        txtRaizMuller.setEditable(false);
        txtRaizMuller.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Error:");

        txtErrorMuller.setEditable(false);
        txtErrorMuller.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblMuller.setModel(new DefaultTableModel());
        tblMuller.setEnabled(false);
        jScrollPane4.setViewportView(tblMuller);

        javax.swing.GroupLayout pnlMullerLayout = new javax.swing.GroupLayout(pnlMuller);
        pnlMuller.setLayout(pnlMullerLayout);
        pnlMullerLayout.setHorizontalGroup(
            pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(pnlMullerLayout.createSequentialGroup()
                        .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        pnlMullerLayout.setVerticalGroup(
            pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMullerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaizMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlBairstow.setBackground(new java.awt.Color(255, 255, 255));
        pnlBairstow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBairstow.setPreferredSize(new java.awt.Dimension(870, 150));

        lblBairstow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairstow.setText("Bairstow");

        txtBairstow.setEditable(false);
        txtBairstow.setColumns(20);
        txtBairstow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBairstow.setRows(5);
        jScrollPane5.setViewportView(txtBairstow);

        javax.swing.GroupLayout pnlBairstowLayout = new javax.swing.GroupLayout(pnlBairstow);
        pnlBairstow.setLayout(pnlBairstowLayout);
        pnlBairstowLayout.setHorizontalGroup(
            pnlBairstowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairstowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBairstowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(pnlBairstowLayout.createSequentialGroup()
                        .addComponent(lblBairstow)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBairstowLayout.setVerticalGroup(
            pnlBairstowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairstowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBairstow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFuncionesLayout = new javax.swing.GroupLayout(pnlFunciones);
        pnlFunciones.setLayout(pnlFuncionesLayout);
        pnlFuncionesLayout.setHorizontalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSecante, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addComponent(pnlTartaglia, javax.swing.GroupLayout.PREFERRED_SIZE, 907, Short.MAX_VALUE)
            .addComponent(pnlHorner, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addComponent(pnlFerrari, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addComponent(pnlMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addComponent(pnlBairstow, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        pnlFuncionesLayout.setVerticalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionesLayout.createSequentialGroup()
                .addComponent(pnlSecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTartaglia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlHorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFerrari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMuller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBairstow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(pnlFunciones);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Limites:");

        txtMin.setEditable(false);
        txtMin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtMax.setEditable(false);
        txtMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Valores incales para Bairstow:");

        txtMinB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMinB.setText("-2");

        txtMaxB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMaxB.setText("-2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaxB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbFunciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtMinB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaxB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tartaglia() {
        int grado;
        double discriminante;
        double[] coef;
        String funcion = String.valueOf(cmbFunciones.getSelectedItem());
        List<Object> raices;
        Tartaglia t = new Tartaglia();
        grado = eva.gradoMayor(funcion);
        coef = eva.obtenerCoeficientes(grado, funcion);
        discriminante = t.calcularDiscriminante(coef[1], coef[2], coef[3]);
        raices = t.calcularRaices(discriminante);

        txtTartaglia1.setText(raices.toArray()[0].toString());
        txtTartaglia2.setText(raices.toArray()[1].toString());
        txtTartaglia3.setText(raices.toArray()[2].toString());
        txtDicriminante.setText(String.valueOf(discriminante));

    }

    public void secante() {
        Secante s = new Secante();
        s.setX0(Double.parseDouble(txtMin.getText()));
        s.setX1(Double.parseDouble(txtMax.getText()));
        DefaultTableModel l = new DefaultTableModel();
        if (cmbFunciones.getSelectedIndex() == 5 || cmbFunciones.getSelectedIndex() == 6) {
            s.setFuncion(String.valueOf(" " + cmbFunciones.getSelectedItem()).replaceAll("x", "*x").replaceAll(" [*]x", " x").replaceFirst(" ", ""));
        } else if (cmbFunciones.getSelectedIndex() == 7 || cmbFunciones.getSelectedIndex() == 8 || cmbFunciones.getSelectedIndex() == 9 || cmbFunciones.getSelectedIndex() == 10) {
            s.setFuncion(String.valueOf(cmbFunciones.getSelectedItem()));
        }
        l.setRowCount(0);
        l = s.n();
        tblSecante.setModel(l);
        txtRaizSecante.setText(tblSecante.getValueAt(tblSecante.getRowCount() - 1, 2).toString());
        txtErrorSecante.setText(tblSecante.getValueAt(tblSecante.getRowCount() - 1, 3).toString());
    }

    public void setExtremos(double n1, double n2) {
        txtMin.setText(String.valueOf(n1));
        txtMax.setText(String.valueOf(n2));
    }

    public void ferrari() {
        int grado;
        double[] coef;
        Ferrari f = new Ferrari();
        String funcion = String.valueOf(cmbFunciones.getSelectedItem());
        List<Double> raices;

        grado = eva.gradoMayor(funcion);
        coef = eva.obtenerCoeficientes(grado, funcion);
        raices = f.ferrari(coef[1], coef[2], coef[3], coef[4]);
        txtFerrari1.setText(String.valueOf(raices.toArray()[0]));
        txtFerrari2.setText(String.valueOf(raices.toArray()[1]));
        txtFerrari3.setText(String.valueOf(raices.toArray()[2]));
        txtFerrari4.setText(String.valueOf(raices.toArray()[3]));
    }

    public void horner() {
        DefaultTableModel dtm = new DefaultTableModel();
        Horner h = new Horner();
        dtm = h.horner(Double.parseDouble(txtMin.getText()), eva.obtenerCoeficientes(eva.gradoMayor(cmbFunciones.getSelectedItem().toString()), cmbFunciones.getSelectedItem().toString()));
        tblHorner.setModel(dtm);
        txtRaizHorner.setText(tblHorner.getValueAt(tblHorner.getRowCount() - 1, 1).toString());
        txtErrorHorner.setText(tblHorner.getValueAt(tblHorner.getRowCount() - 1, 2).toString());
    }

    public void muller() {
        Muller m = new Muller();
        m.setFuncion(cmbFunciones.getSelectedItem().toString());
        m.setX0(Double.parseDouble(txtMin.getText()));
        m.setX1(Double.parseDouble(txtMax.getText()));
        m.setX2(Double.parseDouble(txtMax.getText()) + 0.5);
        tblMuller.setModel(m.calcularRaiz());
        txtRaizMuller.setText(tblMuller.getValueAt(tblMuller.getRowCount() - 1, 3).toString());
        txtErrorMuller.setText(tblMuller.getValueAt(tblMuller.getRowCount() - 1, 4).toString());
    }

    public void bairstow() {
        String funcion = cmbFunciones.getSelectedItem().toString(), raices = "Raices:\n";
        Bairstow b = new Bairstow();
        b.setGrado(eva.gradoMayor(funcion));
        Object[] bair = b.bairstow(Double.parseDouble(txtMinB.getText()), Double.parseDouble(txtMinB.getText()), eva.obtenerCoeficientes(eva.gradoMayor(funcion), funcion));
        for (Object ob : bair) {
            if (ob != null) {
                raices += ob.toString() + "\n";
            }
        }
        if (eva.gradoMayor(funcion) > 4) {
                for (Object obj : b.getRaices2()) {
                    if (obj != null) {
                        raices += obj.toString() + "\n";
                    }
                }
            }
        txtBairstow.setText(raices);
    }

    public void activar(int[] opcion) {
        for (int i : opcion) {
            switch (i) {
                case 1:
                    pnlSecante.show(true);
                    secante();
                    break;
                case 2:
                    pnlTartaglia.show(true);
                    tartaglia();
                    break;
                case 3:
                    pnlFerrari.show(true);
                    ferrari();
                    break;
                case 4:
                    pnlHorner.show(true);
                    horner();
                    break;
                case 5:
                    pnlMuller.show(true);
                    muller();
                    break;
                case 6:
                    pnlBairstow.show(true);
                    bairstow();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "ERROR");
            }
        }
    }

    public void desactivar() {
        pnlBairstow.show(false);
        pnlFerrari.show(false);
        pnlHorner.show(false);
        pnlMuller.show(false);
        pnlTartaglia.show(false);
        pnlSecante.show(false);
    }

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        desactivar();
        switch (cmbFunciones.getSelectedIndex()) {
            case 1:
                setExtremos(0, 1);
                activar(new int[]{2, 4, 5, 6});
                break;
            case 2:
                setExtremos(-3, -0);
                activar(new int[]{2, 4, 5, 6});
                break;
            case 3:
                setExtremos(-2, -1);
                activar(new int[]{3, 4, 5, 6});
                break;
            case 4:
                setExtremos(-3, -2);
                activar(new int[]{3, 4, 5, 6});
                break;
            case 5:
                setExtremos(0, 1);
                activar(new int[]{1, 4, 5, 6});
                break;
            case 6:
                setExtremos(2.9, 2.6);
                activar(new int[]{1, 4, 5, 6});
                break;
            case 7:
                setExtremos(0, 1);
                activar(new int[]{1, 5});
                break;
            case 8:
                setExtremos(2.5, 3);
                activar(new int[]{1, 5});
                break;
            case 9:
                setExtremos(1.2, 1.5);
                activar(new int[]{1, 5});
                break;
            case 10:
                setExtremos(1, 2);
                activar(new int[]{1});
                break;
            default:
                JOptionPane.showMessageDialog(null, "Elija una funcion");
                break;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtFerrari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFerrari3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFerrari3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMetodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JComboBox<String> cmbFunciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBairstow;
    private javax.swing.JPanel pnlBairstow;
    private javax.swing.JPanel pnlFerrari;
    private javax.swing.JPanel pnlFunciones;
    private javax.swing.JPanel pnlHorner;
    private javax.swing.JPanel pnlMuller;
    private javax.swing.JPanel pnlSecante;
    private javax.swing.JPanel pnlTartaglia;
    private javax.swing.JTable tblHorner;
    private javax.swing.JTable tblMuller;
    private javax.swing.JTable tblSecante;
    private javax.swing.JTextArea txtBairstow;
    private javax.swing.JTextField txtDicriminante;
    private javax.swing.JTextField txtErrorHorner;
    private javax.swing.JTextField txtErrorMuller;
    private javax.swing.JTextField txtErrorSecante;
    private javax.swing.JTextField txtFerrari1;
    private javax.swing.JTextField txtFerrari2;
    private javax.swing.JTextField txtFerrari3;
    private javax.swing.JTextField txtFerrari4;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMaxB;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtMinB;
    private javax.swing.JTextField txtRaizHorner;
    private javax.swing.JTextField txtRaizMuller;
    private javax.swing.JTextField txtRaizSecante;
    private javax.swing.JTextField txtTartaglia1;
    private javax.swing.JTextField txtTartaglia2;
    private javax.swing.JTextField txtTartaglia3;
    // End of variables declaration//GEN-END:variables
}
