/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.Evaluador;
import metodos.Ferrari;
import metodos.Secante;
import metodos.Tartaglia;

/**
 *
 * @author villa
 */
public class InterfazMetodos extends javax.swing.JFrame {

    Evaluador eva = new Evaluador();
    String funcionMoficiada;
    Secante s = new Secante();

    /**
     * Creates new form InterfazMetodos
     */
    public InterfazMetodos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbFunciones = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFunciones = new javax.swing.JPanel();
        pnlTartaglia = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTartaglia1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTartaglia2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTartaglia3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDicriminante = new javax.swing.JTextField();
        pnlSecante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRaizSecante = new javax.swing.JTextField();
        txtErrorSecante = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlFerrari = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFerrari3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFerrari2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFerrari1 = new javax.swing.JTextField();
        txtFerrari4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pnlHorner = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlMuller = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlBairstow = new javax.swing.JPanel();
        lblBairstow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        cmbFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una funcion", "x^3 + 3x - 1", "x^3 - 4.65x^2 - 49.92x - 76.69", "x^4 + x^3 + 0.56x^2 - 1.44x - 2.88", "x^4 - 3x^2 + 5x + 2", "x^5 - 3x^4 - 23x^3 + 55x^2 + 74x - 120", "x^6 - 7x^4 + x^3 - 1", "ln(1+x) - cos(x)", "10sen(x) + 3cos(x)", "e^3(x-1) - ln(x-1)2 + 1", "cos(0.785 - x(1+x^2)^1/2 )" }));
        cmbFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFuncionesItemStateChanged(evt);
            }
        });
        cmbFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuncionesActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        pnlFunciones.setBackground(new java.awt.Color(0, 0, 0));

        pnlTartaglia.setBackground(new java.awt.Color(255, 255, 255));
        pnlTartaglia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTartaglia.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tartaglia");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Raiz:");

        txtTartaglia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Raiz:");

        txtTartaglia2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Raiz:");

        txtTartaglia3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Discriminante: ");

        txtDicriminante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlTartagliaLayout = new javax.swing.GroupLayout(pnlTartaglia);
        pnlTartaglia.setLayout(pnlTartagliaLayout);
        pnlTartagliaLayout.setHorizontalGroup(
            pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTartagliaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia3))
                    .addGroup(pnlTartagliaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTartaglia1)))
                .addGap(28, 28, 28)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDicriminante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        pnlTartagliaLayout.setVerticalGroup(
            pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTartagliaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTartaglia1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDicriminante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTartaglia2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTartagliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTartaglia3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(380, 380, 380))
        );

        pnlSecante.setBackground(new java.awt.Color(255, 255, 255));
        pnlSecante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSecante.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Secante");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Raiz:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Error:");

        txtRaizSecante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtErrorSecante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout pnlSecanteLayout = new javax.swing.GroupLayout(pnlSecante);
        pnlSecante.setLayout(pnlSecanteLayout);
        pnlSecanteLayout.setHorizontalGroup(
            pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlSecanteLayout.createSequentialGroup()
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSecanteLayout.setVerticalGroup(
            pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlSecanteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaizSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSecanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorSecante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlFerrari.setBackground(new java.awt.Color(255, 255, 255));
        pnlFerrari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFerrari.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ferrari");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Raiz:");

        txtFerrari3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Raiz:");

        txtFerrari2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Raiz:");

        txtFerrari1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtFerrari4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Raiz:");

        javax.swing.GroupLayout pnlFerrariLayout = new javax.swing.GroupLayout(pnlFerrari);
        pnlFerrari.setLayout(pnlFerrariLayout);
        pnlFerrariLayout.setHorizontalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari2))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari3))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFerrari4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFerrariLayout.setVerticalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFerrari1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFerrari2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFerrari3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFerrari4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHorner.setBackground(new java.awt.Color(255, 255, 255));
        pnlHorner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlHorner.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Horner");

        javax.swing.GroupLayout pnlHornerLayout = new javax.swing.GroupLayout(pnlHorner);
        pnlHorner.setLayout(pnlHornerLayout);
        pnlHornerLayout.setHorizontalGroup(
            pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHornerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHornerLayout.setVerticalGroup(
            pnlHornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHornerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pnlMuller.setBackground(new java.awt.Color(255, 255, 255));
        pnlMuller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMuller.setPreferredSize(new java.awt.Dimension(870, 150));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Muller");

        javax.swing.GroupLayout pnlMullerLayout = new javax.swing.GroupLayout(pnlMuller);
        pnlMuller.setLayout(pnlMullerLayout);
        pnlMullerLayout.setHorizontalGroup(
            pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMullerLayout.setVerticalGroup(
            pnlMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pnlBairstow.setBackground(new java.awt.Color(255, 255, 255));
        pnlBairstow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBairstow.setPreferredSize(new java.awt.Dimension(870, 150));

        lblBairstow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairstow.setText("Bairstow");

        javax.swing.GroupLayout pnlBairstowLayout = new javax.swing.GroupLayout(pnlBairstow);
        pnlBairstow.setLayout(pnlBairstowLayout);
        pnlBairstowLayout.setHorizontalGroup(
            pnlBairstowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairstowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBairstow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBairstowLayout.setVerticalGroup(
            pnlBairstowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairstowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBairstow)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFuncionesLayout = new javax.swing.GroupLayout(pnlFunciones);
        pnlFunciones.setLayout(pnlFuncionesLayout);
        pnlFuncionesLayout.setHorizontalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSecante, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addComponent(pnlTartaglia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnlHorner, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addComponent(pnlFerrari, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addComponent(pnlMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addComponent(pnlBairstow, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        pnlFuncionesLayout.setVerticalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionesLayout.createSequentialGroup()
                .addComponent(pnlSecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTartaglia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlHorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFerrari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMuller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBairstow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(pnlFunciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbFunciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcular)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFuncionesActionPerformed

    private void cmbFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFuncionesItemStateChanged
    }//GEN-LAST:event_cmbFuncionesItemStateChanged

    public void tartaglia() {
        int grado;
        double discriminante;
        double[] coef;
        String funcion = String.valueOf(cmbFunciones.getSelectedItem());
        List<Object> raices;
        Tartaglia t = new Tartaglia();
        grado = eva.gradoMayor(funcion);
        coef = eva.obtenerCoeficientes(grado, funcion);
        discriminante = t.calcularDiscriminante(coef[1], coef[2], coef[3]);
        raices = t.calcularRaices(discriminante);

        System.out.println(Arrays.toString(coef));
        txtTartaglia1.setText(raices.toArray()[0].toString());
        txtTartaglia2.setText(raices.toArray()[1].toString());
        txtTartaglia3.setText(raices.toArray()[2].toString());
        txtDicriminante.setText(String.valueOf(discriminante));

    }
    
    public void secante(){
        DefaultTableModel l = new DefaultTableModel();
        s.setFuncion(String.valueOf(" " + cmbFunciones.getSelectedItem()).replaceAll("x", "*x").replaceAll(" [*]x", " x").replaceFirst(" ", ""));
        l.setRowCount(0);
        l = s.n();
        jTable1.setModel(l);
        txtRaizSecante.setText(jTable1.getValueAt(jTable1.getRowCount()-1, 2).toString());
        txtErrorSecante.setText(jTable1.getValueAt(jTable1.getRowCount()-1, 3).toString());
        System.out.println(String.valueOf(" " + cmbFunciones.getSelectedItem()).replaceAll("x", "*x").replaceAll(" [*]x", " x").replaceFirst(" ", ""));
    }
    
    public void setExtremosSecante(double n1,double n2){
        s.setX0(n1);
        s.setX1(n2);
    }
    
    public void ferrari(){
        int grado;
        double[] coef;
        Ferrari f = new Ferrari();
        String funcion = String.valueOf(cmbFunciones.getSelectedItem());
        List<Double> raices;
        
        grado = eva.gradoMayor(funcion);
        coef = eva.obtenerCoeficientes(grado, funcion);
        System.out.println(Arrays.toString(coef));
        raices = f.ferrari(coef[1],coef[2], coef[3], coef[4]);
        txtFerrari1.setText(String.valueOf(raices.toArray()[0]));
        txtFerrari2.setText(String.valueOf(raices.toArray()[1]));
        txtFerrari3.setText(String.valueOf(raices.toArray()[2]));
        txtFerrari4.setText(String.valueOf(raices.toArray()[3]));
    }
    
    public void activar(int[] opcion) {
        for (int i : opcion) {
            switch (i) {
                case 1:
                    pnlSecante.show(true);
                    secante();
                    break;
                case 2:
                    pnlTartaglia.show(true);
                    tartaglia();
                    break;
                case 3:
                    pnlFerrari.show(true);
                    ferrari();
                    break;
                case 4:
                    pnlHorner.show(true);
                    break;
                case 5:
                    pnlMuller.show(true);
                    break;
                case 6:
                    pnlBairstow.show(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "ERROR");
            }
        }
    }

    public void desactivar() {
        pnlBairstow.show(false);
        pnlFerrari.show(false);
        pnlHorner.show(false);
        pnlMuller.show(false);
        pnlTartaglia.show(false);
        pnlSecante.show(false);
    }

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        desactivar();
        switch (cmbFunciones.getSelectedIndex()) {
            case 1:
                activar(new int[]{2, 4, 5, 6});
                break;
            case 2:
                activar(new int[]{2, 4, 5, 6});
                break;
            case 3:
                activar(new int[]{3, 4, 5, 6});
                break;
            case 4:
                activar(new int[]{3, 4, 5, 6});
                break;
            case 5:
                activar(new int[]{1, 4, 5, 6});
                setExtremosSecante(0, 1);
                break;
            case 6:
                activar(new int[]{1, 4, 5, 6});
                setExtremosSecante(-2.9, -2.5);
                break;
            case 7:
                activar(new int[]{1, 5});
                break;
            case 8:
                activar(new int[]{1, 5});
                break;
            case 9:
                activar(new int[]{1, 5});
                break;
            case 10:
                activar(new int[]{10});
                
                break;
            default:
                JOptionPane.showMessageDialog(null, "Elija una funcion");
                break;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMetodos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMetodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JComboBox<String> cmbFunciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBairstow;
    private javax.swing.JPanel pnlBairstow;
    private javax.swing.JPanel pnlFerrari;
    private javax.swing.JPanel pnlFunciones;
    private javax.swing.JPanel pnlHorner;
    private javax.swing.JPanel pnlMuller;
    private javax.swing.JPanel pnlSecante;
    private javax.swing.JPanel pnlTartaglia;
    private javax.swing.JTextField txtDicriminante;
    private javax.swing.JTextField txtErrorSecante;
    private javax.swing.JTextField txtFerrari1;
    private javax.swing.JTextField txtFerrari2;
    private javax.swing.JTextField txtFerrari3;
    private javax.swing.JTextField txtFerrari4;
    private javax.swing.JTextField txtRaizSecante;
    private javax.swing.JTextField txtTartaglia1;
    private javax.swing.JTextField txtTartaglia2;
    private javax.swing.JTextField txtTartaglia3;
    // End of variables declaration//GEN-END:variables
}
